### ISSUE TITLE
Blank return

### ISSUE THREAD

**Issue by panosru** [fALKENdk/mylocation#11]
I tried it today but it doesn't return the flag of the IP country I am...

I tried using VPN: Greece, Urkaine, Russia, UK, Germany..

![image](https://user-images.githubusercontent.com/400362/52165443-7ef9cd80-2709-11e9-83a0-eab222897667.png)

**Comment by ryanerwin** [comment]
It looks like the freegeoip.net API no longer provides service...
When you visit that site now, you get ipstack.com and they do offer a free api key that allows up to 10,000 request per month... 

The actual query also changed slightly:

https://ipstack.com/documentation

**Comment by fALKENdk** [comment]
Thank you :) Fixed in #14
